### ISSUE TITLE
undefined local variable or method `protocol' 

### ISSUE THREAD

**Issue by charyorde** [cf-platform-eng/cf-containers-broker#18]
Even with a custom config settings.yml, I'm still getting ```undefined local variable or method `protocol' ``` in the logs

**settings.yml**
```
defaults: &defaults
  log_path: 'log/<%= Rails.env %>.log'
  auth_username: 'containers'
  cookie_secret: 'e7247dae-a252-4393-afa3-2219c1c02efd'
  session_expiry: 86400

  cc_api_uri: 'http://api.10.244.0.34.xip.io'
  external_ip: 10.244.0.34
  external_host: 'xip.io'
  external_port: 80
  component_name: 'cf-containers-broker'

  ssl_enabled: false
  skip_ssl_validation: true

  host_directory: '/tmp/store/cf-containers-broker/'
  max_containers: 0

  message_bus_servers:
    - 'nats://10.244.0.6:4222'
```
```
 emperor@emperor:/tmp/cf-containers-broker$ docker run -d --name cf-containers-broker --publish 8585:8585 --volume /var/run:/var/run --volume /tmp/cf-docker-broker/config:/config --volume /tmp/cf-docker-broker/logs:/app/log frodenas/cf-containers-broker               
emperor@emperor:/tmp/cf-containers-broker$ docker logs -f cf-containers-broker                                                                                                                              Fetching Containers Images...
(erb):98:in `<main>': undefined local variable or method `protocol' for main:Object (NameError)
        from /usr/local/lib/ruby/2.1.0/erb.rb:850:in `eval'
        from /usr/local/lib/ruby/2.1.0/erb.rb:850:in `result'
        from /usr/local/lib/ruby/gems/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
        from /usr/local/lib/ruby/gems/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
        from /usr/local/lib/ruby/gems/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
        from /usr/local/lib/ruby/gems/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:66:in `method_missing'
        from /app/config/application.rb:35:in `<class:Application>'
        from /app/config/application.rb:17:in `<module:CfContainersBroker>'
        from /app/config/application.rb:16:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from bin/fetch_container_images:3:in `<main>'
```
